name: CI

on:
  push:
    branches: main
    paths:
      - "packages/**"
      - "yarn.lock"
      - "package.json"
      - ".github/workflows/**"
      - "eslint.config.mjs"
  pull_request:
    paths:
      - "packages/**"
      - "yarn.lock"
      - "package.json"
      - ".github/workflows/**"
      - "eslint.config.mjs"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npm install -g corepack

      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build all packages
        run: yarn build:all

      - name: Lint all packages
        run: yarn lint:all
